// AUTO-GENERATED by scripts/_generate.mjs — standalone runner for Scanner.run.
// Edit the method in classes/Scanner.js, then re-run the generator to refresh.
// Calls Scanner.run(...) directly; no shared engine.
//
// argv[1] is repointed at a phantom entrypoint in the PROJECT ROOT *before* the
// dynamic imports run, because classes/Secrets.js loads .env (and Yamls reads
// config.yml) from dirname(process.argv[1]). scripts/Scanner/ is two levels
// below root, so '..','..' = root.
import path from 'node:path';
process.argv[1] = path.resolve(import.meta.dirname, '..', '..', 'runner.js');

const yargsMod = await import('yargs');
const { hideBin } = await import('yargs/helpers');
const yargs = yargsMod.default;
const { Scanner } = await import('../../classes/Scanner.js');
const { Yamls } = await import('../../classes/Yamls.js');
const { Dates } = await import('../../classes/Dates.js');
const { Dialogs } = await import('../../classes/Dialogs.js');

async function main() {
    console.log('1️⃣ Scanner run Start');

    const argv = yargs(hideBin(process.argv))
        .option("sourceFolder", { describe: "sourceFolder (object key)" })
        .option("aicFolder", { describe: "aicFolder (object key)" })
        .option("maxLevel", { describe: "maxLevel (object key)" })
        .option("exclusions", { describe: "exclusions (object key)" })
        .help()
        .parse();

    const run = async () => {
        const result = await Scanner.run({ ...(argv["sourceFolder"] !== undefined ? { sourceFolder: argv["sourceFolder"] } : {}), ...(argv["aicFolder"] !== undefined ? { aicFolder: argv["aicFolder"] } : {}), ...(argv["maxLevel"] !== undefined ? { maxLevel: argv["maxLevel"] } : {}), ...(argv["exclusions"] !== undefined ? { exclusions: argv["exclusions"] } : {}) });
        if (result !== undefined) console.log('📤 Result:', typeof result === 'object' ? JSON.stringify(result, null, 2) : result);
    };

    if (Yamls.getConfig('CmdLine.TryCatch') === 'true') {
        try {
            await run();
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
        } catch (error) {
            console.error('❌ Error:', error);
            Dialogs.warningBox(error.message, 'Scanner run Error');
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeoutError')));
            process.exit(1);
        }
    } else {
        await run();
        Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
    }

    console.log('3️⃣ Scanner run Done');
}

main();
