// AUTO-GENERATED by runs/_generate.mjs — standalone runner for IjaraSoliq.contracts.
// Edit the method in utils/IjaraSoliq.js, then re-run the generator to refresh.
// Calls IjaraSoliq.contracts(...) directly; no shared engine.
//
// argv[1] is repointed at a phantom entrypoint in the PROJECT ROOT *before* the
// dynamic imports run, because utils/Secrets.js loads .env (and Yamls reads
// config.yml) from dirname(process.argv[1]). runs/IjaraSoliq/ is two levels
// below root, so '..','..' = root.
import path from 'node:path';
process.argv[1] = path.resolve(import.meta.dirname, '..', '..', 'runner.js');

const yargsMod = await import('yargs');
const { hideBin } = await import('yargs/helpers');
const yargs = yargsMod.default;
const { IjaraSoliq } = await import('../../utils/IjaraSoliq.js');
const { Yamls } = await import('../../utils/Yamls.js');
const { Dates } = await import('../../utils/Dates.js');
const { Dialogs } = await import('../../utils/Dialogs.js');

async function main() {
    console.log('1️⃣ IjaraSoliq contracts Start');

    const argv = yargs(hideBin(process.argv))
        .option("owner", { describe: "owner (optional)" })
        .option("rentType", { describe: "rentType (optional)" })
        .option("state", { describe: "state (optional)" })
        .option("page", { describe: "page (optional)" })
        .option("size", { describe: "size (optional)" })
        .help()
        .parse();

    const run = async () => {
        const result = await IjaraSoliq.contracts(argv["owner"], argv["rentType"], argv["state"], argv["page"], argv["size"]);
        if (result !== undefined) console.log('📤 Result:', typeof result === 'object' ? JSON.stringify(result, null, 2) : result);
    };

    if (Yamls.getConfig('CmdLine.TryCatch') === 'true') {
        try {
            await run();
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
        } catch (error) {
            console.error('❌ Error:', error);
            Dialogs.warningBox(error.message, 'IjaraSoliq contracts Error');
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeoutError')));
            process.exit(1);
        }
    } else {
        await run();
        Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
    }

    console.log('3️⃣ IjaraSoliq contracts Done');
}

main();
