// AUTO-GENERATED by runs/_generate.mjs — standalone runner for Scanner.notify.
// Edit the method in utils/Scanner.js, then re-run the generator to refresh.
// Calls Scanner.notify(...) directly; no shared engine.
//
// argv[1] is repointed at a phantom entrypoint in the PROJECT ROOT *before* the
// dynamic imports run, because utils/Secrets.js loads .env (and Yamls reads
// config.yml) from dirname(process.argv[1]). runs/Scanner/ is two levels
// below root, so '..','..' = root.
import path from 'node:path';
process.argv[1] = path.resolve(import.meta.dirname, '..', '..', 'runner.js');

const yargsMod = await import('yargs');
const { hideBin } = await import('yargs/helpers');
const yargs = yargsMod.default;
const { Scanner } = await import('../../utils/Scanner.js');
const { Yamls } = await import('../../utils/Yamls.js');
const { Dates } = await import('../../utils/Dates.js');
const { Dialogs } = await import('../../utils/Dialogs.js');

async function main() {
    console.log('1️⃣ Scanner notify Start');

    const argv = yargs(hideBin(process.argv))
        .option("message", { describe: "message" })
        .option("title", { describe: "title" })
        .option("timeoutSeconds", { describe: "timeoutSeconds" })
        .option("type", { alias: "t", describe: "type (optional)" })
        .help()
        .parse();

    const run = async () => {
        const result = await Scanner.notify(argv["message"], argv["title"], argv["timeoutSeconds"], argv["type"]);
        if (result !== undefined) console.log('📤 Result:', typeof result === 'object' ? JSON.stringify(result, null, 2) : result);
    };

    if (Yamls.getConfig('CmdLine.TryCatch') === 'true') {
        try {
            await run();
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
        } catch (error) {
            console.error('❌ Error:', error);
            Dialogs.warningBox(error.message, 'Scanner notify Error');
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeoutError')));
            process.exit(1);
        }
    } else {
        await run();
        Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
    }

    console.log('3️⃣ Scanner notify Done');
}

main();
