// AUTO-GENERATED by scripts/_generate.mjs — standalone runner for Markdown.merge.
// Edit the method in classes/Markdown.js, then re-run the generator to refresh.
// Calls Markdown.merge(...) directly; no shared engine.
//
// argv[1] is repointed at a phantom entrypoint in the PROJECT ROOT *before* the
// dynamic imports run, because classes/Secrets.js loads .env (and Yamls reads
// config.yml) from dirname(process.argv[1]). scripts/Markdown/ is two levels
// below root, so '..','..' = root.
import path from 'node:path';
process.argv[1] = path.resolve(import.meta.dirname, '..', '..', 'runner.js');

const yargsMod = await import('yargs');
const { hideBin } = await import('yargs/helpers');
const yargs = yargsMod.default;
const { Markdown } = await import('../../classes/Markdown.js');
const { Yamls } = await import('../../classes/Yamls.js');
const { Dates } = await import('../../classes/Dates.js');
const { Dialogs } = await import('../../classes/Dialogs.js');

async function main() {
    console.log('1️⃣ Markdown merge Start');

    const argv = yargs(hideBin(process.argv))
        .command('$0 [files..]', false, (y) => y.positional("files", { array: true, type: 'string' }))
        .option("lineBetween", { describe: "lineBetween (optional)" })
        .help()
        .parse();

    const run = async () => {
        const result = await Markdown.merge(argv["files"] || [], argv["lineBetween"]);
        if (result !== undefined) console.log('📤 Result:', typeof result === 'object' ? JSON.stringify(result, null, 2) : result);
    };

    if (Yamls.getConfig('CmdLine.TryCatch') === 'true') {
        try {
            await run();
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
        } catch (error) {
            console.error('❌ Error:', error);
            Dialogs.warningBox(error.message, 'Markdown merge Error');
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeoutError')));
            process.exit(1);
        }
    } else {
        await run();
        Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
    }

    console.log('3️⃣ Markdown merge Done');
}

main();
