// AUTO-GENERATED by scripts/_generate.mjs — standalone runner for Yamls.computePenalty.
// Edit the method in classes/Yamls.js, then re-run the generator to refresh.
// Calls Yamls.computePenalty(...) directly; no shared engine.
//
// argv[1] is repointed at a phantom entrypoint in the PROJECT ROOT *before* the
// dynamic imports run, because classes/Secrets.js loads .env (and Yamls reads
// config.yml) from dirname(process.argv[1]). scripts/Yamls/ is two levels
// below root, so '..','..' = root.
import path from 'node:path';
process.argv[1] = path.resolve(import.meta.dirname, '..', '..', 'runner.js');

const yargsMod = await import('#yargs');
const { hideBin } = await import('#yargs-helpers');
const yargs = yargsMod.default;
const { Yamls } = await import('../../classes/Yamls.js');
const { Dates } = await import('../../classes/Dates.js');
const { Dialogs } = await import('../../classes/Dialogs.js');

async function main() {
    console.log('1️⃣ Yamls computePenalty Start');

    const argv = yargs(hideBin(process.argv))
        .option("penaltyDays", { describe: "penaltyDays" })
        .option("penaltyForDay", { describe: "penaltyForDay" })
        .option("priceMaxApp", { describe: "priceMaxApp" })
        .help()
        .parse();

    const run = async () => {
        const result = await Yamls.computePenalty(argv["penaltyDays"], argv["penaltyForDay"], argv["priceMaxApp"]);
        if (result !== undefined) console.log('📤 Result:', typeof result === 'object' ? JSON.stringify(result, null, 2) : result);
    };

    if (Yamls.getConfig('CmdLine.TryCatch') === 'true') {
        try {
            await run();
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
        } catch (error) {
            console.error('❌ Error:', error);
            Dialogs.warningBox(error.message, 'Yamls computePenalty Error');
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeoutError')));
            process.exit(1);
        }
    } else {
        await run();
        Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
    }

    console.log('3️⃣ Yamls computePenalty Done');
}

main();
