// AUTO-GENERATED by runs/_generate.mjs — standalone runner for MySoliq.entrepreneurInfo.
// Edit the method in utils/MySoliq.js, then re-run the generator to refresh.
// Calls MySoliq.entrepreneurInfo(...) directly; no shared engine.
//
// argv[1] is repointed at a phantom entrypoint in the PROJECT ROOT *before* the
// dynamic imports run, because utils/Secrets.js loads .env (and Yamls reads
// config.yml) from dirname(process.argv[1]). runs/MySoliq/ is two levels
// below root, so '..','..' = root.
import path from 'node:path';
process.argv[1] = path.resolve(import.meta.dirname, '..', '..', 'runner.js');

const yargsMod = await import('yargs');
const { hideBin } = await import('yargs/helpers');
const yargs = yargsMod.default;
const { MySoliq } = await import('../../utils/MySoliq.js');
const { Yamls } = await import('../../utils/Yamls.js');
const { Dates } = await import('../../utils/Dates.js');
const { Dialogs } = await import('../../utils/Dialogs.js');

async function main() {
    console.log('1️⃣ MySoliq entrepreneurInfo Start');

    const argv = yargs(hideBin(process.argv))
        .option("pinfl", { describe: "pinfl" })
        .option("passportSeries", { describe: "passportSeries" })
        .option("passportNumber", { describe: "passportNumber" })
        .help()
        .parse();

    const run = async () => {
        const result = await MySoliq.entrepreneurInfo(argv["pinfl"], argv["passportSeries"], argv["passportNumber"]);
        if (result !== undefined) console.log('📤 Result:', typeof result === 'object' ? JSON.stringify(result, null, 2) : result);
    };

    if (Yamls.getConfig('CmdLine.TryCatch') === 'true') {
        try {
            await run();
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
        } catch (error) {
            console.error('❌ Error:', error);
            Dialogs.warningBox(error.message, 'MySoliq entrepreneurInfo Error');
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeoutError')));
            process.exit(1);
        }
    } else {
        await run();
        Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
    }

    console.log('3️⃣ MySoliq entrepreneurInfo Done');
}

main();
