// AUTO-GENERATED by runs/_generate.mjs — standalone runner for PowerPoints.merge.
// Edit the method in utils/PowerPoints.js, then re-run the generator to refresh.
// Calls PowerPoints.merge(...) directly; no shared engine.
//
// argv[1] is repointed at a phantom entrypoint in the PROJECT ROOT *before* the
// dynamic imports run, because utils/Secrets.js loads .env (and Yamls reads
// config.yml) from dirname(process.argv[1]). runs/PowerPoints/ is two levels
// below root, so '..','..' = root.
import path from 'node:path';
process.argv[1] = path.resolve(import.meta.dirname, '..', '..', 'runner.js');

const yargsMod = await import('yargs');
const { hideBin } = await import('yargs/helpers');
const yargs = yargsMod.default;
const { PowerPoints } = await import('../../utils/PowerPoints.js');
const { Yamls } = await import('../../utils/Yamls.js');
const { Dates } = await import('../../utils/Dates.js');
const { Dialogs } = await import('../../utils/Dialogs.js');

async function main() {
    console.log('1️⃣ PowerPoints merge Start');

    const argv = yargs(hideBin(process.argv))
        .command('$0 [filePaths..]', false, (y) => y.positional("filePaths", { array: true, type: 'string' }))
        .option("name", { describe: "mergedName (optional)" })
        .help()
        .parse();

    const run = async () => {
        const result = await PowerPoints.merge(argv["filePaths"] || [], argv["name"]);
        if (result !== undefined) console.log('📤 Result:', typeof result === 'object' ? JSON.stringify(result, null, 2) : result);
    };

    if (Yamls.getConfig('CmdLine.TryCatch') === 'true') {
        try {
            await run();
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
        } catch (error) {
            console.error('❌ Error:', error);
            Dialogs.warningBox(error.message, 'PowerPoints merge Error');
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeoutError')));
            process.exit(1);
        }
    } else {
        await run();
        Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
    }

    console.log('3️⃣ PowerPoints merge Done');
}

main();
