// AUTO-GENERATED by runs/_generate.mjs — standalone runner for Dialogs.warningBox.
// Edit the method in utils/Dialogs.js, then re-run the generator to refresh.
// Calls Dialogs.warningBox(...) directly; no shared engine.
//
// argv[1] is repointed at a phantom entrypoint in the PROJECT ROOT *before* the
// dynamic imports run, because utils/Secrets.js loads .env (and Yamls reads
// config.yml) from dirname(process.argv[1]). runs/Dialogs/ is two levels
// below root, so '..','..' = root.
import path from 'node:path';
process.argv[1] = path.resolve(import.meta.dirname, '..', '..', 'runner.js');

const yargsMod = await import('yargs');
const { hideBin } = await import('yargs/helpers');
const yargs = yargsMod.default;
const { Dialogs } = await import('../../utils/Dialogs.js');
const { Yamls } = await import('../../utils/Yamls.js');
const { Dates } = await import('../../utils/Dates.js');

async function main() {
    console.log('1️⃣ Dialogs warningBox Start');

    const argv = yargs(hideBin(process.argv))
        .option("message", { describe: "message" })
        .option("title", { describe: "title (optional)" })
        .option("icon", { describe: "icon (optional)" })
        .option("buttons", { describe: "buttons (optional)" })
        .option("stop", { describe: "stop (optional)" })
        .help()
        .parse();

    const run = async () => {
        const result = await Dialogs.warningBox(argv["message"], argv["title"], argv["icon"], argv["buttons"], argv["stop"]);
        if (result !== undefined) console.log('📤 Result:', typeof result === 'object' ? JSON.stringify(result, null, 2) : result);
    };

    if (Yamls.getConfig('CmdLine.TryCatch') === 'true') {
        try {
            await run();
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
        } catch (error) {
            console.error('❌ Error:', error);
            Dialogs.warningBox(error.message, 'Dialogs warningBox Error');
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeoutError')));
            process.exit(1);
        }
    } else {
        await run();
        Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
    }

    console.log('3️⃣ Dialogs warningBox Done');
}

main();
