// AUTO-GENERATED by runs/_generate.mjs — standalone runner for Excels.replaceStandart.
// Edit the method in utils/Excels.js, then re-run the generator to refresh.
// Calls Excels.replaceStandart(...) directly; no shared engine.
//
// argv[1] is repointed at a phantom entrypoint in the PROJECT ROOT *before* the
// dynamic imports run, because utils/Secrets.js loads .env (and Yamls reads
// config.yml) from dirname(process.argv[1]). runs/Excels/ is two levels
// below root, so '..','..' = root.
import path from 'node:path';
process.argv[1] = path.resolve(import.meta.dirname, '..', '..', 'runner.js');

const yargsMod = await import('yargs');
const { hideBin } = await import('yargs/helpers');
const yargs = yargsMod.default;
const { Excels } = await import('../../utils/Excels.js');
const { Yamls } = await import('../../utils/Yamls.js');
const { Dates } = await import('../../utils/Dates.js');
const { Dialogs } = await import('../../utils/Dialogs.js');

async function main() {
    console.log('1️⃣ Excels replaceStandart Start');

    const argv = yargs(hideBin(process.argv))
        .option("file", { alias: "f", describe: "filePath" })
        .option("search", { alias: "s", describe: "searchStr (optional)" })
        .option("replace", { alias: "r", describe: "replaceStr (optional)" })
        .option("recalc", { describe: "recalc (optional)" })
        .option("sheet", { describe: "sheetFilter (optional)" })
        .help()
        .parse();

    const run = async () => {
        const result = await Excels.replaceStandart(argv["file"], argv["search"], argv["replace"], argv["recalc"], argv["sheet"]);
        if (result !== undefined) console.log('📤 Result:', typeof result === 'object' ? JSON.stringify(result, null, 2) : result);
    };

    if (Yamls.getConfig('CmdLine.TryCatch') === 'true') {
        try {
            await run();
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
        } catch (error) {
            console.error('❌ Error:', error);
            Dialogs.warningBox(error.message, 'Excels replaceStandart Error');
            Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeoutError')));
            process.exit(1);
        }
    } else {
        await run();
        Dates.sleep(Number(Yamls.getConfig('CmdLine.ExitTimeout')));
    }

    console.log('3️⃣ Excels replaceStandart Done');
}

main();
